os: linux
language: ruby
rvm:
  - 2.3.8
  # - 2.4.9
  # - 2.5.7
  # - 2.6.5
  # - 2.7.0
  # - ruby-head
notifications:
  email: false

gemfile:
  - gemfiles/sidekiq_3.3.1.gemfile
  # - gemfiles/sidekiq_3.x.gemfile
  # - gemfiles/sidekiq_4.x.gemfile
  # - gemfiles/sidekiq_5.x.gemfile
  # - gemfiles/sidekiq_6.x.gemfile
  # - gemfiles/sidekiq_head.gemfile

jobs:
  include:
    - rvm: "2.6.5"
      gemfile: "gemfiles/sidekiq_5.x.gemfile"
      env:
        - CODECLIMATE_REPORT=true
    - stage: helm-chart
      language: shell
      before_install:
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      script:
        - mkdir -p out
        - helm lint helm-charts/*
        - helm package helm-charts/* -d out
        - helm repo index --url https://mikhailadvani.github.io/sidekiq-prometheus-exporter/ out
        - pwd
        - ls
        - find .
      after_success: []
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        verbose: true
        on:
          branch: master

  exclude:
    - rvm: "2.3.8"
      gemfile: "gemfiles/sidekiq_6.x.gemfile"
    - rvm: "2.4.9"
      gemfile: "gemfiles/sidekiq_6.x.gemfile"
    - rvm: "2.3.8"
      gemfile: "gemfiles/sidekiq_head.gemfile"
    - rvm: "2.4.9"
      gemfile: "gemfiles/sidekiq_head.gemfile"
    - rvm: "2.5.7"
      gemfile: "gemfiles/sidekiq_head.gemfile"
    - rvm: "2.6.5"
      gemfile: "gemfiles/sidekiq_head.gemfile"
    - rvm: "2.7.0"
      gemfile: "gemfiles/sidekiq_head.gemfile"
  allow_failures:
    - rvm: "ruby-head"
      gemfile: "gemfiles/sidekiq_head.gemfile"

cache:
  directories:
    - ./vendor

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN

before_install:
  - gem install bundler -v '~> 2.1'

before_script:
  - if [ ! -f ./vendor/cc-test-reporter ]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./vendor/cc-test-reporter;
    chmod +x ./vendor/cc-test-reporter;
    fi
  - if [ ! -z "$CODECLIMATE_REPORT" ]; then
    echo "Start recording Codeclimate test coverage";
    ./vendor/cc-test-reporter before-build;
    fi
script:
  - bundle exec rake spec
after_success:
  - if [ ! -z "$CODECLIMATE_REPORT" ]; then
    echo "Finish recording Codeclimate test coverage";
    ./vendor/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi

# - os: linux
#   language: minimal
#   jobs:
#     include:
#       - stage: helm-chart
#         before_install:
#           - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
#           - chmod 700 get_helm.sh
#           - ./get_helm.sh
#         script:
#           - mkdir -p out && helm lint helm-charts/* && helm package helm-charts/* -d out && helm repo index --url https://mikhailadvani.github.io/sidekiq-prometheus-exporter/ out
#         deploy:
#           provider: pages
#           cleanup: false
#           github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#           keep_history: true
#           local_dir: out
#           on:
#             branch: helm-repo
